services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/microservice/static
      - /etc/ssl:/etc/ssl
    restart: "on-failure"
    networks:
      - deterrers

  web:
    depends_on:
      - nginx
    build: 
      context: ./application
      dockerfile: Dockerfile
    command: gunicorn application.wsgi:application --workers=13 --threads=1 --bind 0.0.0.0:8000
    env_file:
      - ./.prod.env
    image: deterrers-application
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker container
      - static_volume:/home/app/microservice/static
      - ./db:/home/app/microservice/db
      - ./logs:/home/app/microservice/logs
    expose:
      - 8000
    restart: "on-failure"
    networks:
      - deterrers

  supercronic:
    depends_on:
      - web
    build: 
      context: ./application
      dockerfile: Dockerfile-supercronic
    env_file:
      - ./.prod.env
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker container
      - ./db:/home/app/microservice/db
      - ./logs:/home/app/microservice/logs
    restart: "on-failure"

volumes:
  static_volume:

networks:
  deterrers:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
  default: