version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"

  web:
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn deterrerssite.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    image: deterrers-application
    # volumes:
    #   - ./deterrers-app/:/usr/src/app/
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
    expose:
      - 8000
    restart: "on-failure"

volumes:
 static_volume: