version: "3"

services:
  web:
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile.prod
    command: gunicorn deterrerssite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./deterrers-app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web