version: "3"

services:
  web:
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    image: deterrers-application
    restart: "on-failure"

volumes:
 static_volume: