version: "3"

services:

  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - 8000:8000
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./vpn:/vpn
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["/sbin/tini", "--", "/usr/bin/openvpn.sh", "-d"]

  nginx:
    build: ./nginx
    ports:
      - 80:81
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"

  web:
    depends_on:
      - vpn
    network_mode: "service:vpn"
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: gunicorn deterrerssite.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    image: deterrers-application
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
      - ./db:/home/app/microservice/db
    # expose:
    #   - 8000
    restart: "on-failure"

volumes:
  static_volume:

networks:
  default: