version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:81
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"

  web:
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: gunicorn deterrerssite.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    image: deterrers-application
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
      - ./db:/home/app/microservice/db
    expose:
      - 8000
    restart: "on-failure"

volumes:
  static_volume: