version: "3"

services:

  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - vpn_bridge
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - 80:80
    expose:
      - 8000
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./vpn:/vpn
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["/sbin/tini", "--", "/usr/bin/openvpn.sh", "-d"]

  web:
    depends_on:
      - vpn
    network_mode: "service:vpn"
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    env_file:
      - ./.env.dev
    image: deterrers-application
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
      # - ./db:/home/app/microservice/db
      # - ./logs:/home/app/microservice/logs
    restart: "on-failure"

volumes:
 static_volume:

networks:
  vpn_bridge: