version: "3"

services:

  dev-web:
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:89
    ports:
      - 89:89
    env_file:
      - ./.env.dev
    image: deterrers-application
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
      - ./dev-db:/home/app/microservice/db
      - ./dev-logs:/home/app/microservice/logs
    restart: "on-failure"

  dev-supercronic:
    depends_on:
      - dev-web
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile-supercronic
    env_file:
      - ./.env.dev
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - ./logs:/home/app/microservice/logs
    restart: "on-failure"

volumes:
 static_volume:
