version: "3"

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/microservice/static
      - /etc/ssl:/etc/ssl
    restart: "on-failure"

  web:
    depends_on:
      - nginx
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile
    command: gunicorn deterrerssite.wsgi:application --workers=13 --threads=1 --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    image: deterrers-application
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
      - ./db:/home/app/microservice/db
      - ./logs:/home/app/microservice/logs
    expose:
      - 8000
    restart: "on-failure"

  supercronic:
    depends_on:
      - web
    build: 
      context: ./deterrers-app
      dockerfile: Dockerfile-supercronic
    env_file:
      - ./.env.prod
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - ./logs:/home/app/microservice/logs
    restart: "on-failure"

volumes:
  static_volume:
